const i18Obj = {
  'en': {
    'about': 'About',
    'skills': 'Skills',
    'code': 'Code',
    'cats': 'Cats',
    'experience': "Experience",
    'download': 'Download CV',
    'profile': 'Profile',
    'projects': 'Projects',
    'contacts': 'Contacts',
    'name': 'Grygorii Lysytsia',
    'location': 'Russia, Rostov-on-Don',
    'schedule': 'Open for remote and office work',
    'bem': 'BEM',
    'adaptive': 'Adaptive and responsive layouts',
    'optimization': 'Webpage optimization',
    'js': 'JS Basic',
    'downloadlinken': 'Download CV (English)',
    'downloadlinkru': 'Download CV (Russian)',
    'english': 'English (Intermediate - B1)',
    'interests': 'Intrests',
    'videogames': 'Video Games',
    'books': 'Books',
    'tvshows': 'TV shows',
    'self-education': 'Self-education',
    'profiletext': "I have been working in aviation for 6 years and after all this time and after the contract ended, I realized that do not want to continue and I was tenting to be a developer. I was spending all my free time to exposure to this wonderful world of front-end development after 10 or 12 work shifts. I realized that this process tenting me, and I do not feel tired after learning new and reinforcing old knowledge. I am on my way to becoming a qualified developer, I do not stop learning new skills and new technologies. My way is to become tech lead because I want to be a professional, to understand all the subtleties and pitfalls, positive and negative sides of using any technology when you need to use proper and right techs. Difficulties do not frighten me, but only strengthen my fuse because when you overcome something difficult, you feel this victory over something difficult that sometimes seems impossible for others. I like this feeling when they come to you for advice and see you as a highly qualified person, my motto in life is 'There is no limit to perfection'",
    'ice-cream': 'Ice-cream shop',
    'eduactionproject': 'Education project from HTML academy',
    'githublink': 'Github link',
    'electronicsshop': 'Electronics shop',
    'toyshop': 'Toy shop',
    'adaptive2': 'Adaptive',
    'optimization2': 'Optimization',
    'companionservice': 'Сompanion search service "Pognali"',
    'codexample': 'Code example',
    'codexampletext1': 'A man has a rather old car being worth $2000. He saw a secondhand car being worth $8000. He wants to keep his old car until he can buy the secondhand one.',
    'codexampletext2': 'He thinks he can save $1000 each month but the prices of h old car and of the new one decrease of 1.5 percent per month. Furthermore this percent of loss increases of 0.5 percent at the end of every two months. Our man finds it difficult to makeis all these calculations.',
    'codexampletext3': 'Can you help him? How many months will it take him to save up enough money to buy the car he wants, and how much money will he have left over?',
    'education1': 'Donetsk National University',
    'education2': 'Historical faculty',
    'education3': 'Specialist International relations and foreign policy (Bachelor)',
    'education4': 'Specialist International relations and foreign policy (Specialist)',
    'selfeducation': 'Self-education and courses',
    'selfeducationtext1': 'HTML, CSS, JS in HTML academy',
    'selfeducationtext2': 'Udemy course “The Complete Web Developer in 2022: Zero to Mastery”',
    'selfeducationdate1': 'Present',
    'selfeducationtext4': 'The Rolling Scopes JavaScript/Front-end',
    'selfeducationtext5': 'The Rolling Scopes JavaScript/Front-end. Stage 0',
    'keksobooking': 'Service for looking for appartments in Tokyo "Keksobooking"',
    'modules': 'JS modules',
    'packages': 'Using JS libraries'
  },
  'ru': {
    'about': 'Коротко обо мне',
    'cats': 'Коты',
    'skills': 'Навыки',
    'code': 'Код',
    'experience': "Опыт работы",
    'downloadlinken': 'Скачать CV (Английский)',
    'downloadlinkru': 'Скачать CV (Русский)',
    'download': 'Скачать резюме',
    'profile': 'Коротко обо мне',
    'projects': 'Проекты',
    'contacts': 'Контакты',
    'name': 'Григорий Лисица',
    'location': 'Россия, Ростов-на-Дону',
    'schedule': 'Работа в офисе или удаленная',
    'bem': 'БЭМ',
    'adaptive': 'Адаптивный и отзывчивый дизайн',
    'optimization': 'Оптимазиация страницы',
    'js': 'Основы JS',
    'english': 'Английский (Средний - B1)',
    'interests': 'Увлечения',
    'videogames': 'Видеоигры',
    'books': 'Книги',
    'tvshows': 'ТВ шоу',
    'self-education': 'Самообразование',
    'profiletext': "Проработав 6 лет в авиационной сфере и по истечению контракта, я понял что больше не хочу этим заниматься и меня тянет в сторону разработки. Приходя после 10 а иногда и 12 часовой смены я тратил все свое свободное время на погружения в этот дивный мир Фонтэнда. Я понял что этот процесс меня очень сильно затягивает и я не устаю от изучения нового и закрепления своих знаний. Сейчас я нахожусь на пути становления полноценным разработчиком, не перестаю изучать все новые и современные технологии разработки. Мой путь ведет меня к становлению техническим лидером так как я хочу быть профессионалом своего дела и понимать все тонкости, особенности, положительные и отрицательный стороны той или иной технологии, когда их стоит использовать, а когда это уже будет черезчур. Трудности меня не пугают, а только усиливают мой запал, ведь когда ты преодолеваешь что-то трудное ты чувствуешь эту победу над чем-то сложным что для других иногда кажеться не возможным. Мне нравиться это чувство когда к тебе приходят за советом и видят в тебе высококвалифицированного человека, мой девиз по жизни «Нет пределу соверщенству»",
    'ice-cream': 'Магазин мороженного',
    'eduactionproject': 'Обучающий проект из HTML academy',
    'githublink': 'Ссылка на гитхаб',
    'electronicsshop': 'Магазин электроники',
    'toyshop': 'Магазин игрушек',
    'adaptive2': 'Адаптивность',
    'optimization2': 'Оптимизация',
    'companionservice': 'Сервис поиска попутчиков "Погнали"',
    'codexample': 'Пример кода',
    'codexampletext1': 'У человека довольно старая машина стоимостью 2000 долларов. Он увидел подержанную машину стоимостью 8000 долларов. Он хочет сохранить свою старую машину, пока не купит подержанную.',
    'codexampletext2': 'Он думает, что сможет экономить 1000 долларов каждый месяц, но цены на старую машину и на новую уменьшаются на 1,5 процента в месяц. Кроме того, этот процент потерь увеличивается на 0,5 процента в конце каждых двух месяцев. Нашему человеку трудно произвести все эти расчеты.',
    'codexampletext3': 'Вы можете помочь ему? Сколько месяцев ему понадобится, чтобы накопить достаточно денег, чтобы купить машину, которую он хочет, и сколько денег у него останется?',
    'education1': 'Донецкий Национальный Университет',
    'education2': 'Исторический факультет',
    'education3': 'Кафедра международных отношений и внешней политики (Бакалавриат)',
    'education4': 'Кафедра международных отношений и внешней политики (Специалитет)',
    'selfeducation': 'Самообразование и курсы',
    'selfeducationtext1': 'HTML, CSS, JS в HTML academy',
    'selfeducationtext2': 'Курс на Udemy “The Complete Web Developer in 2022: Zero to Mastery”',
    'selfeducationdate1': 'по настоящее время',
    'selfeducationtext3': 'Книга по JS',
    'selfeducationtext4': 'The Rolling Scopes Курс JavaScript/Front-end',
    'selfeducationtext5': 'The Rolling Scopes Подготовительный курс JavaScript/Front-end. Stage 0',
    'keksobooking': 'Сервис по поиску жилья в Токио "Кексобукинг"',
    'modules': 'JS модули',
    'packages': 'Использование JS библиотек'
  }
}
export default i18Obj;
