const i18Obj = {
  'en': {
    'about': 'About',
    'skills': 'Skills',
    'code': 'Code',
    'cats': 'Cats',
    'experience': "Experience",
    'download': 'Download CV',
    'profile': 'Profile',
    'projects': 'Projects',
    'contacts': 'Contacts',
    'name': 'Grygorii Lysytsia',
    'location': 'Russia, Rostov-on-Don',
    'schedule': 'Open for remote and office work',
    'bem': 'BEM',
    'adaptive': 'Adaptive and responsive layouts',
    'optimization': 'Webpage optimization',
    'js': 'JavaScript',
    'downloadlinken': 'Download CV (English)',
    'downloadlinkru': 'Download CV (Russian)',
    'english': 'English (Intermediate - B1)',
    'interests': 'Intrests',
    'videogames': 'Video Games',
    'books': 'Books',
    'tvshows': 'TV shows',
    'self-education': 'Self-education',
    'profiletext1': "I worked in aviation for 6 years and after all this time and after the contract ended, I realized that I don’t want to continue and I really want to be a Frontend developer. I’m spending all my free time honing and deepening my knowledge at Frontend.",
    'profiletext2': "In the next 5 years, I see myself as tech lead because I want to be a professional, to understand all the subtleties and pitfalls, positive and negative sides of using any technology when you need to use the proper and right tech.",
    'profiletext3': "Difficulties are exciting me, because when you overcome something difficult, you feel this victory over something hard that sometimes seems impossible for others. I like this feeling when they come to you for advice and see you as a highly qualified person.",
    'profiletext4': "My life motto is 'There is no limit to perfection'.",
    'ice-cream': 'Ice-cream shop',
    'eduactionproject': 'Education project from HTML academy',
    'githublink': 'Github link',
    'electronicsshop': 'Electronics shop',
    'toyshop': 'Toy shop',
    'adaptive2': 'Adaptive',
    'optimization2': 'Optimization',
    'companionservice': 'Сompanion search service "Pognali"',
    'codexample': 'Code example',
    'codexampletext1': 'A man has a rather old car being worth $2000. He saw a secondhand car being worth $8000. He wants to keep his old car until he can buy the secondhand one.',
    'codexampletext2': 'He thinks he can save $1000 each month but the prices of h old car and of the new one decrease of 1.5 percent per month. Furthermore this percent of loss increases of 0.5 percent at the end of every two months. Our man finds it difficult to makeis all these calculations.',
    'codexampletext3': 'Can you help him? How many months will it take him to save up enough money to buy the car he wants, and how much money will he have left over?',
    'education1': 'Donetsk National University',
    'education2': 'Historical faculty',
    'education3': 'Specialist International relations and foreign policy (Bachelor)',
    'education4': 'Specialist International relations and foreign policy (Specialist)',
    'selfeducation': 'Self-education and courses',
    'selfeducationtext1': 'HTML, CSS, JS in HTML academy',
    'selfeducationtext2': 'Udemy course “The Complete Web Developer in 2022: Zero to Mastery”',
    'selfeducationdate1': 'Present',
    'selfeducationtext4': 'The Rolling Scopes JavaScript/Front-end',
    'selfeducationtext5': 'The Rolling Scopes JavaScript/Front-end. Stage 0',
    'selfeducationtext6': 'JavaScript Architecture of Front-end applications',
    'selfeducationtext7': 'React. Development of complex front-end applications',
    'keksobooking': 'Housing search service in Tokyo "Keksobooking"',
    'modules': 'JS modules',
    'packages': 'Using JS libraries',
    'patterns': 'Programming patterns',
    'Drink 2GO': 'Coffee shop "Drink 2GO"',
    'gradingproject': 'Grading project from HTML academy',
    'MVP': 'MVP pattern',
    'testing': 'Jest testing',
    'cinemaadict': '"Cinemaadict" website, who loves cinema',
    'server': 'Work with server',
    'catalog-project': 'My own catalog project (Based on HTML draft)',
    'wtw': 'Online cinema "What to watch"',
    'education': 'Education',
    'sedona-nuxt': 'Sedona, project completed on Nuxt(I took only design from education project)',
    'experience-period': 'Period:',
    'experience-organization': 'Organization:',
    'experience-occupation': 'Occupation:',
    'experience-duties': 'Duties:',
    'experience-duties-1': 'I have extensive experience in developing user SPA pages using Vue 3 Composition API. I am proficient in working with tools such as vue-router and Vuex to manage application routing and state, respectively.',
    'experience-duties-2': 'I have successfully conducted project migrations to Vue 3, including updating existing code and seamlessly adapting to the new functionality. I possess the skills necessary for a smooth transition to the latest framework version.',
    'experience-duties-3': 'Experience in enhancing and supporting existing Vue 2 pages is part of my responsibilities. This includes error resolution, performance optimization, and the addition of new features in Vue 2 projects.',
    'experience-duties-4': "I have implemented and maintained the Gulp + esBuild build system to enhance the project's build process. My experience has led to a 30% increase in build speed compared to using webpack. Additionally, I provide technical support for this build system, regularly update it, and add new functionality in accordance with project requirements.",
    'experience-duties-5': 'I have implemented linters and developed a code guide and code style to ensure consistent and clean code within the project. I adhere to best development practices and actively work on improving code quality within the team.',
    'experience-duties-6': 'I have experience in developing projects using TypeScript, applying a non-intrusive approach. My proficiency in TypeScript enhances code safety and maintainability, reduces the number of errors, and improves collaboration with colleagues.',
    'experience-duties-7': 'I also have experience in developing projects and solving tasks using vanilla JavaScript, without the use of frameworks or libraries.',
    'experience-period-desc': 'November 2022 - Present',
    'experience-organization-desc': 'RANEPA',
    'experience-occupation-desc': 'Technician',
  },
  'ru': {
    'about': 'Коротко обо мне',
    'cats': 'Коты',
    'skills': 'Навыки',
    'code': 'Код',
    'experience': "Опыт работы",
    'downloadlinken': 'Скачать CV (Английский)',
    'downloadlinkru': 'Скачать CV (Русский)',
    'download': 'Скачать резюме',
    'profile': 'Коротко обо мне',
    'projects': 'Проекты',
    'contacts': 'Контакты',
    'name': 'Григорий Лисица',
    'location': 'Россия, Ростов-на-Дону',
    'schedule': 'Работа в офисе или удаленная',
    'bem': 'БЭМ',
    'adaptive': 'Адаптивный и отзывчивый дизайн',
    'optimization': 'Оптимизиация страницы',
    'js': 'JavaScript',
    'english': 'Английский (Средний - B1)',
    'interests': 'Увлечения',
    'videogames': 'Видеоигры',
    'books': 'Книги',
    'tvshows': 'ТВ шоу',
    'self-education': 'Самообразование',
    'profiletext1': "Проработав 6 лет в авиационной сфере и по истечению контракта, я понял, что больше не хочу этим заниматься и я хочу стать Фронтенд разработчиком. Я посвящаю все свое свободное время на оттачивание и углубления своих знаний во Фронтенде.",
    'profiletext2': "В ближайшие 5 лет я вижу себя как тех лида так как я хочу быть профессионалом своего дела: понимать все тонкости, особенности, положительные и отрицательный стороны той или иной технологии, когда их стоит использовать, а когда это уже будет чересчур.",
    'profiletext3': "Трудности меня вдохновляют, ведь когда ты преодолеваешь что-то трудное ты чувствуешь эту победу над чем-то сложным что для других иногда кажется не возможным. Мне нравиться это чувство, когда к тебе приходят за советом и видят в тебе высококвалифицированного человека.",
    'profiletext4': "Мой девиз по жизни «Нет предела совершенству».",
    'ice-cream': 'Магазин мороженного',
    'eduactionproject': 'Обучающий проект из HTML academy',
    'githublink': 'Ссылка на гитхаб',
    'electronicsshop': 'Магазин электроники',
    'toyshop': 'Магазин игрушек',
    'adaptive2': 'Адаптивность',
    'optimization2': 'Оптимизация',
    'companionservice': 'Сервис поиска попутчиков "Погнали"',
    'codexample': 'Пример кода',
    'codexampletext1': 'У человека довольно старая машина стоимостью 2000 долларов. Он увидел подержанную машину стоимостью 8000 долларов. Он хочет сохранить свою старую машину, пока не купит подержанную.',
    'codexampletext2': 'Он думает, что сможет экономить 1000 долларов каждый месяц, но цены на старую машину и на новую уменьшаются на 1,5 процента в месяц. Кроме того, этот процент потерь увеличивается на 0,5 процента в конце каждых двух месяцев. Нашему человеку трудно произвести все эти расчеты.',
    'codexampletext3': 'Вы можете помочь ему? Сколько месяцев ему понадобится, чтобы накопить достаточно денег, чтобы купить машину, которую он хочет, и сколько денег у него останется?',
    'education1': 'Донецкий Национальный Университет',
    'education2': 'Исторический факультет',
    'education3': 'Кафедра международных отношений и внешней политики (Бакалавриат)',
    'education4': 'Кафедра международных отношений и внешней политики (Специалитет)',
    'selfeducation': 'Самообразование и курсы',
    'selfeducationtext1': 'HTML, CSS, JS в HTML academy',
    'selfeducationtext2': 'Курс на Udemy “The Complete Web Developer in 2022: Zero to Mastery”',
    'selfeducationdate1': 'по настоящее время',
    'selfeducationtext3': 'Книга по JS',
    'selfeducationtext4': 'The Rolling Scopes Курс JavaScript/Front-end',
    'selfeducationtext5': 'The Rolling Scopes Подготовительный курс JavaScript/Front-end. Stage 0',
    'selfeducationtext6': 'JavaScript. Архитектура клиентских приложений',
    'selfeducationtext7': 'React. Разработка сложных клиентских приложений',
    'keksobooking': 'Сервис по поиску жилья в Токио "Кексобукинг"',
    'modules': 'JS модули',
    'packages': 'Использование JS библиотек',
    'patterns': 'Паттерны программирования',
    'Drink 2GO': 'Магазин кофе "Dring 2GO"',
    'gradingproject': 'Проект грейдирования из HTML academy',
    'MVP': 'MVP паттерн',
    'testing': 'Jest тестирование',
    'cinemaadict': 'Киноман, вэбсайт для любителей кино',
    'server': 'Работа с сервером',
    'catalog-project': 'Мой проект страницы каталога (Основан на макете из HTML academy)',
    'wtw': 'Онлайн кинотеатр "What to watch"',
    'education': 'Обучение',
    'sedona-nuxt': 'Sedona, переделанный проект на Nuxt(Только макет был взят из обучения)',
    'experience-period': 'Период:',
    'experience-organization': 'Организация:',
    'experience-occupation': 'Должность:',
    'experience-duties': 'Обязанности:',
    'experience-duties-1': 'Обладаю глубоким опытом разработки пользовательских SPA страниц с использованием Vue 3 Composition API. Уверенно работаю с инструментами, такими как vue-router и Vuex, для управления маршрутизацией и состоянием приложения соответственно.',
    'experience-duties-2': 'Успешно проводил миграцию проектов на Vue 3, включая обновление существующего кода и успешную адаптацию к новой функциональности. Владею навыками, необходимыми для эффективного перехода на новую версию фреймворка.',
    'experience-duties-3': 'Опыт доработки и поддержки существующих страниц на Vue 2. Исправление ошибок, оптимизация производительности и добавление новых функций — все это часть моих ответственностей в проектах на Vue 2.',
    'experience-duties-4': "Внедрение и поддержка сборщика Gulp + esBuild для улучшения процесса сборки проекта. Мой опыт позволил увеличить скорость сборки на 30% по сравнению с использованием webpack. Также я осуществляю техническую поддержку этого сборщика, регулярно обновляю его и добавляю новый функционал в соответствии с требованиями проекта.",
    'experience-duties-5': 'Внедрение линтеров и разработка code guide и code style для обеспечения единообразного и чистого кода в проекте. Следую лучшим практикам разработки и активно работаю над улучшением качества кода в команде.',
    'experience-duties-6': 'Обладаю опытом разработки проектов с использованием TypeScript, применяя неагрессивный подход. Мое владение TypeScript позволяет повысить безопасность и поддерживаемость кода, снижая количество ошибок и улучшая работу с коллегами.',
    'experience-duties-7': 'Также имею опыт разработки на ванильном JavaScript без использования фреймворков или библиотек для создания проектов и решения задач.',
    'experience-period-desc': 'Ноябрь 2022 - по настоящее время',
    'experience-organization-desc': 'РАНХиГС',
    'experience-occupation-desc': 'Техник',
  }
}
export default i18Obj;
